feature:Cards (wind, pressure, visibilty, humidity)
Norali-Meriles/weatherReporters pull request #2
Opened 2022-09-28 14:36 UTC by elnegrochoque

2022-09-28 22:01 UTC, CecyD requested changes
Borrar estilos en linea (Infocards.js line 14, 21, 29, 35.
Borrar componente select.js

2022-09-28 23:32 UTC, elnegrochoque commented
cambios realizados

2022-09-29 00:46 UTC, CecyD approved these changes

2022-09-29 14:24 UTC, miqueas35 reviewed
passed

2022-09-29 14:26 UTC, miqueas35 approved these changes
ahora si aprobado

2022-09-29 14:40 UTC, merged